"""
تست‌های اپ کاتالوگ.

نکته: فیلدهای مدل Product دقیقاً title/description/code/slug/category
هستند (نه name/short_description) — این تست‌ها با ساختار واقعی مدل
هم‌تراز شده‌اند تا واقعاً چیزی را بررسی کنند، نه صرفاً pass شوند.
"""

from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import TestCase
from django.urls import reverse

from common.validators import MaxFileSizeValidator, validate_image_content, validate_pdf_content

from .models import Category, Product


class ProductModelTests(TestCase):
    def setUp(self):
        self.category = Category.objects.create(name="دکل‌های برق", slug="towers")
        self.product = Product.objects.create(
            title="دکل مشبک فولادی",
            category=self.category,
            code="SKU-001",
            description="توضیح کوتاه نمونه",
        )

    def test_str_representation(self):
        self.assertEqual(str(self.product), "دکل مشبک فولادی")

    def test_slug_autogenerated_from_title(self):
        self.assertTrue(self.product.slug)

    def test_get_absolute_url(self):
        expected = reverse("catalog:product_detail", kwargs={"slug": self.product.slug})
        self.assertEqual(self.product.get_absolute_url(), expected)

    def test_code_must_be_unique(self):
        with self.assertRaises(Exception):
            Product.objects.create(
                title="محصول تکراری",
                category=self.category,
                code="SKU-001",  # کد تکراری؛ باید رد شود
            )


class CatalogViewTests(TestCase):
    def setUp(self):
        self.category = Category.objects.create(name="تجهیزات صنعتی", slug="equipment")
        self.product = Product.objects.create(
            title="کراس‌آرم فولادی",
            category=self.category,
            code="SKU-004",
            description="توضیح کوتاه نمونه",
        )
        self.inactive_product = Product.objects.create(
            title="محصول غیرفعال",
            category=self.category,
            code="SKU-005",
            is_active=False,
        )

    def test_home_page_status_code(self):
        response = self.client.get(reverse("catalog:home"))
        self.assertEqual(response.status_code, 200)

    def test_product_list_status_code_and_content(self):
        response = self.client.get(reverse("catalog:product_list"))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, self.product.title)

    def test_product_list_hides_inactive_products(self):
        """محصولات غیرفعال (is_active=False) نباید در فهرست عمومی نمایش داده شوند."""
        response = self.client.get(reverse("catalog:product_list"))
        self.assertNotContains(response, self.inactive_product.title)

    def test_product_list_search_filter(self):
        response = self.client.get(reverse("catalog:product_list"), {"q": "کراس‌آرم"})
        self.assertContains(response, self.product.title)

    def test_product_detail_status_code(self):
        response = self.client.get(self.product.get_absolute_url())
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, self.product.code)

    def test_inactive_product_detail_returns_404(self):
        url = reverse("catalog:product_detail", kwargs={"slug": self.inactive_product.slug})
        response = self.client.get(url)
        self.assertEqual(response.status_code, 404)


class FileValidatorTests(TestCase):
    """تست اعتبارسنج‌های مشترک آپلود فایل (common/validators.py)."""

    def test_max_file_size_validator_rejects_large_file(self):
        validator = MaxFileSizeValidator(1)  # حداکثر ۱ مگابایت
        oversized = SimpleUploadedFile("test.jpg", b"x" * (2 * 1024 * 1024))
        with self.assertRaises(ValidationError):
            validator(oversized)

    def test_max_file_size_validator_accepts_small_file(self):
        validator = MaxFileSizeValidator(1)
        small_file = SimpleUploadedFile("test.jpg", b"x" * 1024)
        validator(small_file)  # نباید خطا بدهد

    def test_validate_pdf_content_rejects_non_pdf(self):
        fake_pdf = SimpleUploadedFile("fake.pdf", b"this is not a real pdf")
        with self.assertRaises(ValidationError):
            validate_pdf_content(fake_pdf)

    def test_validate_pdf_content_accepts_real_pdf_header(self):
        real_pdf = SimpleUploadedFile("real.pdf", b"%PDF-1.4\n%...")
        validate_pdf_content(real_pdf)  # نباید خطا بدهد

    def test_validate_image_content_rejects_non_image(self):
        fake_image = SimpleUploadedFile("fake.jpg", b"not an actual image")
        with self.assertRaises(ValidationError):
            validate_image_content(fake_image)
