# Generated by Django 6.0.7

import django.core.validators
from django.db import migrations, models

import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='در صورت خالی گذاشتن، خودکار از روی عنوان ساخته می\u200cشود.', max_length=220, unique=True, verbose_name='اسلاگ')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='کارفرما')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='محل اجرا')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(projects.models.current_year_plus_one)], verbose_name='سال اجرا')),
                ('image', models.ImageField(blank=True, null=True, upload_to=projects.models.project_image_upload_to, verbose_name='تصویر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / نمایش در سایت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='projects_pr_slug_6c2d3a_idx'),
        ),
    ]
