# Generated by Django 6.0.7

from django.db import migrations, models

import certificates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان گواهینامه')),
                ('image', models.ImageField(blank=True, null=True, upload_to=certificates.models.certificate_image_upload_to, verbose_name='تصویر')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / نمایش در سایت')),
            ],
            options={
                'verbose_name': 'گواهینامه',
                'verbose_name_plural': 'گواهینامه\u200cها',
                'ordering': ['-issue_date'],
            },
        ),
    ]
